const text = [
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum ex excepturi exercitationem velit saepe, cumque quaerat accusantium doloremque voluptate consequuntur voluptatum voluptates doloribus? Beatae aut voluptatem corrupti sequi dicta labore, vitae commodi, esse eaque, magnam voluptatum minima voluptatibus optio eos. Tenetur adipisci porro voluptate distinctio inventore. Quasi minima excepturi magnam numquam autem nobis amet inventore qui quidem doloremque sed aliquid facere eum officia aliquam, sequi adipisci temporibus dolor perspiciatis fugiat fuga distinctio natus! Obcaecati!`,
    
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto cupiditate porro, nihil sapiente sit ipsa. Accusantium, fuga. Dolorum porro deleniti atque, iusto ducimus nisi illum cum nihil, nostrum corrupti, totam magnam. Porro fugit veritatis sint sunt minus eos totam numquam id tenetur ad. Exercitationem necessitatibus provident accusantium, numquam sapiente animi aperiam omnis ex. Eveniet sint eos eligendi? Recusandae magni sequi, sint repellat, totam placeat perspiciatis quas itaque dicta iusto quasi et eum sit, dolore similique in modi dolorum tenetur rerum officia! Explicabo necessitatibus neque repellendus eius dignissimos nostrum culpa expedita!`,
    `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta debitis neque, ipsa enim aliquam doloremque ducimus temporibus sed quas commodi, impedit itaque laboriosam vel minima tempora explicabo, aperiam dolor corporis modi. In quidem sunt repudiandae, recusandae minus eius laborum explicabo debitis consequatur laboriosam hic! Harum nulla debitis, sint nostrum quis eius repellendus deserunt, corrupti cumque accusamus labore sit explicabo repellat!`,

    `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem molestias cupiditate consequuntur illo veritatis! Fugit, consequatur eaque harum laborum nostrum omnis ipsum incidunt laboriosam officia voluptatem voluptates adipisci velit assumenda repudiandae quasi nam recusandae, at earum nisi. Inventore provident magnam soluta blanditiis adipisci, veniam quae. Possimus quam soluta amet dolorem labore suscipit, molestiae ad ducimus. Nihil, exercitationem sequi temporibus delectus architecto ipsam, consequuntur maiores quo natus mollitia a earum. Qui magnam in ipsa porro consectetur!`,

    `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, illum! Similique ex ullam nisi exercitationem animi, quis excepturi, numquam facere harum ea porro accusantium iste illum? Numquam quidem laborum enim! Eos nisi eius distinctio accusamus facilis sequi itaque aut placeat?`,

    `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Possimus, accusamus laborum explicabo facere quae voluptatem minima quod sapiente! Ex aliquid, nihil dignissimos neque dolore quia ratione fugit temporibus nisi tempore reprehenderit pariatur. Aliquid, molestiae modi explicabo, necessitatibus nobis similique iusto inventore quasi cupiditate dolore iure dolorem consequuntur, esse ipsa provident unde doloremque voluptate deserunt at. Deserunt laudantium corporis qui iusto error nesciunt nihil maxime exercitationem.`,

    `Lorem, ipsum dolor sit amet consectetur adipisicing elit. A ipsa minima aperiam facere maiores quam voluptate ut porro quas, ipsum accusantium fugit debitis veniam non. Assumenda, quod consectetur facilis beatae expedita maxime obcaecati eius natus doloribus numquam totam similique dignissimos blanditiis nostrum voluptate iste explicabo dolor vitae! Necessitatibus harum numquam perferendis itaque eveniet sint dignissimos magni sit soluta voluptatum accusamus beatae assumenda fuga nam natus, asperiores neque sequi fugit minus. Nam, aperiam amet dolores itaque tempora cupiditate quas ducimus omnis hic fugiat consectetur in nulla quisquam voluptatem fuga ullam ratione quos necessitatibus eveniet at! Dolor aliquam impedit qui consequatur praesentium!`,

    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi repudiandae ut nobis doloribus numquam illo ullam saepe consectetur laborum. Officia praesentium enim iure incidunt aliquid aliquam, id laudantium nihil culpa doloremque voluptas ipsam laborum earum libero tempora iusto sit quam ex fugiat cupiditate placeat, sunt fuga ipsum minima? Debitis saepe, consectetur fugit blanditiis, officia ipsum numquam ex id accusamus reprehenderit ea odio aliquid asperiores enim rerum nulla eveniet nam est. Nemo repellendus provident, accusantium officia illo quo impedit doloremque aspernatur, iste blanditiis eum obcaecati error ipsum ipsam facere accusamus.`,
    `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci saepe praesentium debitis pariatur, repellat veniam! Vitae similique nulla harum libero saepe dolorem consectetur ad, ullam nesciunt, repellendus voluptas! Eius aperiam quaerat, repellat est doloribus tenetur eaque? Tempora explicabo veritatis nam.`
]

export default text